# Generated by Django 3.2.5 on 2021-07-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_post_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
