# Generated by Django 3.2.5 on 2021-07-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_post_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expiry_date',
            field=models.DateField(default='2021-07-29'),
        ),
    ]
